### ISSUE TITLE
Install error loop on Raspberry Pi

### ISSUE THREAD

**Issue by Joymaker** [oscaracena/pygattlib#32]
**pip3 install gattlib**
The following  error repeats indefinitely.  This comes after fixing a previous repeating error by manually installing glib-2.0 with
sudo apt-get install libglib2.0-dev

Seems that some dependencies are not working for this package.

```
$ pip3 install gattlib
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting gattlib
  Using cached gattlib-0.20201113.tar.gz (50 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-73gozool/gattlib_fd2c6403b5d248e585f1f9788ecd08c9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-73gozool/gattlib_fd2c6403b5d248e585f1f9788ecd08c9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-h79solts
         cwd: /tmp/pip-install-73gozool/gattlib_fd2c6403b5d248e585f1f9788ecd08c9/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-73gozool/gattlib_fd2c6403b5d248e585f1f9788ecd08c9/setup.py", line 62, in <module>
        boost_py = get_boost_version()
      File "/tmp/pip-install-73gozool/gattlib_fd2c6403b5d248e585f1f9788ecd08c9/setup.py", line 15, in get_boost_version
        out = subprocess.check_output(
      File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.9/subprocess.py", line 528, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command 'ldconfig -p | grep -E 'libboost_python.*\.so '' returned non-zero exit status 1.
```

My system:
Linux pi 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux
Python 3.9.2

**Comment by dave-p** [comment]
You don't need to install it manually any more, gattlib is now available in RpiOS Bullseye as python3-gattlib.

**Comment by Mas9311** [comment]
setup.py, line 16, remove the trailing space from `.so '`
