### ISSUE TITLE
Segfault on `g_io_channel_get_buffer_condition()`, from GLib

### ISSUE THREAD

**Issue by oscaracena** [oscaracena/pygattlib#5]
It's not a deterministic problem, I don't have a minimal working example to reproduce it. I have a service, and when it runs for a while (sometimes 5 minutes, sometimes seconds), then unexpectedly crashes. I've managed to get a traceback, but it is not of much help:

```gdb
Thread 2 "python" received signal SIGSEGV, Segmentation fault.
[Cambiando a Thread 0x7ffff4db0700 (LWP 61787)]
0x00007ffff4ecd1a4 in g_io_channel_get_buffer_condition () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff4ecd1a4 in g_io_channel_get_buffer_condition () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff4f27de9 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4edb72f in g_main_context_prepare () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4edc0db in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff4edc533 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff500582c in IOService::operator()() ()
   from /usr/lib/python3/dist-packages/gattlib.cpython-38-x86_64-linux-gnu.so
#6  0x00007ffff5a2b43b in ?? () from /lib/x86_64-linux-gnu/libboost_thread.so.1.71.0
#7  0x00007ffff7d82609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7ebe293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Everything happened outside of the library scope. I suspect it is an early-deallocated object.

**Comment by jsgh** [comment]
Hmm. What *else* was going on at the time ("thread apply all bt")?

**Comment by oscaracena** [comment]
Here we go, all threads activity:

```gdb
Thread 2 "python" received signal SIGSEGV, Segmentation fault.
[Cambiando a Thread 0x7ffff4dae700 (LWP 15184)]
0x00007ffff4ecb1a4 in g_io_channel_get_buffer_condition () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) thread apply all bt

Thread 3 (Thread 0x7fffeffff700 (LWP 15186)):
#0  0x00007ffff4ecb0ad in g_io_create_watch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff4ecb105 in g_io_add_watch_full () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff5013639 in ?? () from /usr/lib/python3/dist-packages/gattlib.cpython-38-x86_64-linux-gnu.so
#3  0x00007ffff5013d33 in g_attrib_send () from /usr/lib/python3/dist-packages/gattlib.cpython-38-x86_64-linux-gnu.so
#4  0x00007ffff5012d7c in gatt_write_char () from /usr/lib/python3/dist-packages/gattlib.cpython-38-x86_64-linux-gnu.so
#5  0x00007ffff5007ae4 in GATTRequester::write_by_handle(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /usr/lib/python3/dist-packages/gattlib.cpython-38-x86_64-linux-gnu.so
#6  0x00007ffff4ffc01f in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<boost::python::list (GATTRequester::*)(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), boost::python::default_call_policies, boost::mpl::vector4<boost::python::list, GATTRequester&, unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::operator()(_object*, _object*) () from /usr/lib/python3/dist-packages/gattlib.cpython-38-x86_64-linux-gnu.so
#7  0x00007ffff4e67eab in boost::python::objects::function::call(_object*, _object*) const () from /lib/x86_64-linux-gnu/libboost_python38.so.1.71.0
#8  0x00007ffff4e6815c in ?? () from /lib/x86_64-linux-gnu/libboost_python38.so.1.71.0
#9  0x00007ffff4e6d2eb in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /lib/x86_64-linux-gnu/libboost_python38.so.1.71.0
#10 0x00007ffff4ff742c in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<GATTException, void (*)(GATTException const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(GATTException const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () from /usr/lib/python3/dist-packages/gattlib.cpython-38-x86_64-linux-gnu.so
#11 0x00007ffff4e6d2bb in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /lib/x86_64-linux-gnu/libboost_python38.so.1.71.0
#12 0x00007ffff4ff73cc in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<BTIOException, void (*)(BTIOException const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(BTIOException const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () from /usr/lib/python3/dist-packages/gattlib.cpython-38-x86_64-linux-gnu.so
#13 0x00007ffff4e6d203 in boost::python::handle_exception_impl(boost::function0<void>) () from /lib/x86_64-linux-gnu/libboost_python38.so.1.71.0
#14 0x00007ffff4e656c6 in ?? () from /lib/x86_64-linux-gnu/libboost_python38.so.1.71.0
#15 0x00000000005f46d6 in _PyObject_MakeTpCall ()
#16 0x000000000050a9a3 in ?? ()
#17 0x0000000000570286 in _PyEval_EvalFrameDefault ()
#18 0x00000000005f7146 in _PyFunction_Vectorcall ()
#19 0x000000000056b399 in _PyEval_EvalFrameDefault ()
#20 0x00000000005f7146 in _PyFunction_Vectorcall ()
#21 0x000000000056b399 in _PyEval_EvalFrameDefault ()
#22 0x00000000005f7146 in _PyFunction_Vectorcall ()
#23 0x000000000056b399 in _PyEval_EvalFrameDefault ()
#24 0x00000000005f7146 in _PyFunction_Vectorcall ()
#25 0x000000000056b399 in _PyEval_EvalFrameDefault ()
#26 0x00000000005f7146 in _PyFunction_Vectorcall ()
#27 0x000000000050a24c in ?? ()
#28 0x00000000005f3d42 in PyObject_Call ()
#29 0x000000000056ca92 in _PyEval_EvalFrameDefault ()
#30 0x00000000005f7146 in _PyFunction_Vectorcall ()
#31 0x000000000056b399 in _PyEval_EvalFrameDefault ()
#32 0x00000000005f7146 in _PyFunction_Vectorcall ()
#33 0x000000000056b399 in _PyEval_EvalFrameDefault ()
#34 0x00000000005f7146 in _PyFunction_Vectorcall ()
#35 0x000000000056b399 in _PyEval_EvalFrameDefault ()
#36 0x00000000005f7146 in _PyFunction_Vectorcall ()
#37 0x000000000056b399 in _PyEval_EvalFrameDefault ()
#38 0x00000000005f7146 in _PyFunction_Vectorcall ()
#39 0x000000000050a24c in ?? ()
#40 0x00000000005f3d42 in PyObject_Call ()
#41 0x000000000065561c in ?? ()
#42 0x00000000006750c8 in ?? ()
#43 0x00007ffff7d82609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#44 0x00007ffff7ebe293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7ffff4dae700 (LWP 15184)):
#0  0x00007ffff4ecb1a4 in g_io_channel_get_buffer_condition () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff4f25de9 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4ed972f in g_main_context_prepare () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4eda0db in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff4eda533 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff500382c in IOService::operator()() () from /usr/lib/python3/dist-packages/gattlib.cpython-38-x86_64-linux-gnu.so
#6  0x00007ffff5a2943b in ?? () from /lib/x86_64-linux-gnu/libboost_thread.so.1.71.0
#7  0x00007ffff7d82609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7ebe293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff7bd0740 (LWP 15179)):
#0  0x00007ffff7eb412b in __GI___select (nfds=0, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=0x7fffffffdf00) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x000000000061df8e in ?? ()
#2  0x00000000005c4b10 in ?? ()
#3  0x0000000000570286 in _PyEval_EvalFrameDefault ()
#4  0x00000000005f7146 in _PyFunction_Vectorcall ()
#5  0x000000000056b399 in _PyEval_EvalFrameDefault ()
#6  0x000000000056955a in _PyEval_EvalCodeWithName ()
#7  0x000000000068c4a7 in PyEval_EvalCode ()
#8  0x000000000067bc91 in ?? ()
#9  0x000000000067bd0f in ?? ()
#10 0x000000000067bdcb in PyRun_FileExFlags ()
#11 0x000000000067de4e in PyRun_SimpleFileExFlags ()
#12 0x00000000006b6032 in Py_RunMain ()
#13 0x00000000006b63bd in Py_BytesMain ()
#14 0x00007ffff7dc30b3 in __libc_start_main (main=0x4eea30 <main>, argc=2, argv=0x7fffffffe618, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe608) at ../csu/libc-start.c:308
#15 0x00000000005fa4de in _start ()
(gdb)
```
